const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";

export {
    GET_MOVIES_FAILURE,
    GET_MOVIES_SUCCESS,
    GET_MOVIES_REQUEST
}